name: API Contract Check

on:
  pull_request:
    branches: [huma]
  workflow_dispatch:

jobs:
  check-api:
    runs-on: ubuntu-latest
    env:
      ALLOW_BREAKING_CHANGE: ${{ contains(github.event.pull_request.labels.*.name, 'allow-breaking-change') }}

    steps:
      - uses: actions/checkout@v6
      - run: git fetch --depth=1 origin ${{ github.base_ref }}

      - run: scripts/generate-openapi-spec.sh

      - uses: oasdiff/oasdiff-action/breaking@v0.0.31
        with:
          base: "origin/${{ github.base_ref }}:api/openapi.yaml"
          revision: "api/openapi.generated.yaml"
          fail-on: ${{ env.ALLOW_BREAKING_CHANGE && '' || 'ERR' }}
