name: "Generate OpenAPI Spec on Merge"
on:
  push:
    branches: [huma]

jobs:
  generate-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: git fetch --depth=1 origin ${{ github.base_ref }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Generate new OpenAPI Spec document
        run: go run cmd/generate-openapi-spec/main.go --filename api/openapi.yaml
