name: "Generate OpenAPI Spec"
on:
  push:
    branches:
      - "**"

jobs:
  generate-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: git fetch --depth=1 origin ${{ github.base_ref }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25

      - name: Generate new OpenAPI Spec document
        run: go run cmd/generate-openapi-spec/main.go --filename api/openapi.yaml

      - name: Commit Generated Spec
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.norerply.github.com"
          git add api/openapi.yaml
          git commit -m "Update OpenAPI spec [skip ci]" || echo "No changes to commit"

      - name: Push Updated Spec
        run: git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
